# Default values are shown commented-out.
# To override the default, uncomment the line and edit the value.

[settings]

# You can specify an alternative screen locker here.

# NOTE: arguments to commands may not contain spaces, even if quoted!
# eg this will not work:
# XORG_LOCK_SCREEN_COMMAND="command --'two words'"
# No kind of quoting or escaping will help you here!

# Define screen lockers separately for X11 or Wayland:

#XORG_LOCK_SCREEN_COMMAND="dm-tool lock"
#WAYLAND_LOCK_SCREEN_COMMAND="dm-tool lock"

# Known tested alternatives for xorg: "i3lock", "slock", "xscreensaver-command -lock"
# XORG_LOCK_SCREEN_COMMAND=(xfce4-screensaver-command --lock)
# Wayland alternatives:
# WAYLAND_LOCK_SCREEN_COMMAND=(gtklock -d)
# WAYLAND_LOCK_SCREEN_COMMAND='swaylock -F -f --indicator-idle-visible  -i /usr/share/images/bunsen/wallpapers/default/default'

[showbutton]
# Choose which buttons to display in the yad exit dialog.
# The appropriate commands will be passed to logind.
# However, the buttons currently set to "false" have not been tested and
# may not work with certain hardware and/or software.
# Forum discussion here: https://forums.bunsenlabs.org/viewtopic.php?id=9042

#logout = true
#lock = true
#suspend = true
#hibernate = false
#hybrid-sleep = false
#suspend-then-hibernate = false
#reboot = true
#poweroff = true
